=== strolch-li/strolch/model/src/main/resources/StrolchModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://strolch.li/schema/StrolchModel.xsd"
           xmlns="https://strolch.li/schema/StrolchModel.xsd"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:annotation>
        <xs:documentation>This is Version 2.0 of the StrolchModel XSD.</xs:documentation>
    </xs:annotation>

    <xs:element name="StrolchModel" type="StrolchModelType"/>

    <xs:complexType name="StrolchModelType">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:choice>
                <xs:element type="IncludeFileType" name="IncludeFile" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element type="OrderType" name="Order" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element type="ResourceType" name="Resource" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element type="ActivityType" name="Activity" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="IncludeFileType">
        <xs:attribute type="xs:string" name="file"/>
    </xs:complexType>

    <xs:complexType name="VersionType">
        <xs:attribute type="xs:int" name="Version" use="required"/>
        <xs:attribute type="xs:string" name="CreatedBy" use="required"/>
        <xs:attribute type="xs:string" name="UpdatedBy" use="required"/>
        <xs:attribute type="xs:dateTime" name="Created" use="required"/>
        <xs:attribute type="xs:dateTime" name="Updated" use="required"/>
        <xs:attribute type="xs:string" name="Deleted" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
            <xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
        <xs:attribute type="xs:dateTime" name="Date" use="optional"/>
        <xs:attribute type="StateType" name="State" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ResourceType">
        <xs:sequence>
            <xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
            <xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="TimedStateType" name="TimedState" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
    </xs:complexType>

    <xs:complexType name="ActivityType">
        <xs:sequence>
            <xs:element type="VersionType" name="Version" maxOccurs="1" minOccurs="0"/>
            <xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:choice>
                    <xs:element type="ActionType" name="Action" maxOccurs="unbounded" minOccurs="0"/>
                    <xs:element type="ActivityType" name="Activity" maxOccurs="unbounded" minOccurs="0"/>
                </xs:choice>
            </xs:sequence>
            <xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
        <xs:attribute type="TimeOrderingType" name="TimeOrdering" use="required"/>
    </xs:complexType>

    <xs:complexType name="ActionType">
        <xs:sequence>
            <xs:element type="ParameterBagType" name="ParameterBag" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="PoliciesType" name="Policies" maxOccurs="1" minOccurs="0"/>
            <xs:element type="ValueChangeType" name="ValueChange" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="ResourceId" use="optional"/>
        <xs:attribute type="xs:string" name="ResourceType" use="optional"/>
        <xs:attribute type="StateType" name="State" use="optional"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
    </xs:complexType>

    <xs:complexType name="ParameterBagType">
        <xs:sequence>
            <xs:element type="ParameterType" name="Parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="xs:string" name="Type" use="required"/>
    </xs:complexType>

    <xs:complexType name="ParameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Id" use="required"/>
                <xs:attribute type="xs:string" name="Name" use="required"/>
                <xs:attribute type="ParameterValueType" name="Type" use="required"/>
                <xs:attribute type="xs:string" name="Value" use="optional"/>
                <xs:attribute type="xs:string" name="Interpretation" use="optional"/>
                <xs:attribute type="xs:string" name="Uom" use="optional"/>
                <xs:attribute type="xs:boolean" name="Hidden" use="optional"/>
                <xs:attribute type="xs:int" name="Index" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="PoliciesType">
        <xs:sequence>
            <xs:element type="PolicyType" name="Policy" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PolicyType">
        <xs:attribute type="xs:string" name="Type" use="required"/>
        <xs:attribute type="xs:string" name="Value" use="required"/>
    </xs:complexType>

    <xs:complexType name="TimedStateType">
        <xs:sequence>
            <xs:element type="ValueType" name="Value" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Id" use="required"/>
        <xs:attribute type="xs:string" name="Name" use="required"/>
        <xs:attribute type="TimedStateTypeType" name="Type" use="required"/>
        <xs:attribute type="xs:string" name="Interpretation" use="optional"/>
        <xs:attribute type="xs:string" name="Uom" use="optional"/>
        <xs:attribute type="xs:boolean" name="Hidden" use="optional"/>
        <xs:attribute type="xs:int" name="Index" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ValueType">
        <xs:attribute type="xs:dateTime" name="Time" use="required"/>
        <xs:attribute type="xs:string" name="Value" use="required"/>
    </xs:complexType>

    <xs:complexType name="ValueChangeType">
        <xs:attribute type="xs:string" name="StateId" use="optional"/>
        <xs:attribute type="xs:dateTime" name="Time" use="required"/>
        <xs:attribute type="xs:string" name="Value" use="required"/>
        <xs:attribute type="TimedStateTypeType" name="Type" use="required"/>
    </xs:complexType>

    <xs:simpleType name="StateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Created"/>
            <xs:enumeration value="Planning"/>
            <xs:enumeration value="Planned"/>
            <xs:enumeration value="Execution"/>
            <xs:enumeration value="Stopped"/>
            <xs:enumeration value="Warning"/>
            <xs:enumeration value="Error"/>
            <xs:enumeration value="Executed"/>
            <xs:enumeration value="Closed"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TimeOrderingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Series"/>
            <xs:enumeration value="Parallel"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ParameterValueType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Text"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="Date"/>
            <xs:enumeration value="Duration"/>
            <xs:enumeration value="StringList"/>
            <xs:enumeration value="IntegerList"/>
            <xs:enumeration value="FloatList"/>
            <xs:enumeration value="LongList"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TimedStateTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="FloatList"/>
            <xs:enumeration value="StringSet"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== strolch-li/strolch/model/src/test/resources/data/StrolchModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<StrolchModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://strolch.li/schema/StrolchModel.xsd"
              xsi:schemaLocation="https://strolch.li/schema/StrolchModel.xsd https://strolch.li/xsd/StrolchModel-2.0.xsd">

    <Order Id="@test1" Name="Test Order" Type="Order">
        <ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
            <Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true"/>
        </ParameterBag>
    </Order>
    <Resource Id="@test1" Name="Test Resource" Type="Resource">
        <ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
            <Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true"/>
        </ParameterBag>
    </Resource>

    <IncludeFile file="resources/Resources.xml"/>
    <IncludeFile file="orders/Orders.xml"/>
    <IncludeFile file="activities/Activities.xml"/>

</StrolchModel>

=== strolch-li/strolch/model/src/test/resources/data/resources/Resources.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<StrolchModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://strolch.li/schema/StrolchModel.xsd"
              xsi:schemaLocation="https://strolch.li/schema/StrolchModel.xsd https://strolch.li/xsd/StrolchModel-2.0.xsd">

    <IncludeFile file="Templates.xml"/>

    <Resource Id="MyTestResource" Name="Test Name" Type="TestType">
        <ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
            <Parameter Id="@param9" Name="Text Param" Type="Text"><![CDATA[here we have the content

and some more


content over multiple lines]]></Parameter>
            <Parameter Id="@param8" Name="Duration Param" Type="Duration" Value="P1D"/>
            <Parameter Id="@param7" Name="StringList Param" Type="StringList" Value="Hello;World"/>
            <Parameter Id="@param6" Name="Date Param" Type="Date" Value="2012-11-30T18:12:05.628+01:00"/>
            <Parameter Id="@param5" Name="String Param" Type="String" Value="Strolch"/>
            <Parameter Id="@param4" Name="Long Param" Type="Long" Value="4453234566"/>
            <Parameter Id="@param3" Name="Integer Param" Type="Integer" Value="77"/>
            <Parameter Id="@param2" Name="Float Param" Type="Float" Value="44.3"/>
            <Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true"/>
        </ParameterBag>
        <TimedState Id="@booleanState" Name="Boolean State" Type="Boolean">
            <Value Time="1970-01-01T00:00:00.000+01:00" Value="false"/>
            <Value Time="1970-01-01T00:01:00.000+01:00" Value="true"/>
            <Value Time="1970-01-01T00:02:00.000+01:00" Value="false"/>
        </TimedState>
        <TimedState Id="@integerState" Name="Integer State" Type="Integer">
            <Value Time="1970-01-01T00:00:00.000+01:00" Value="1"/>
            <Value Time="1970-01-01T00:01:00.000+01:00" Value="2"/>
            <Value Time="1970-01-01T00:02:00.000+01:00" Value="3"/>
            <Value Time="1970-01-01T00:03:00.000+01:00" Value="2"/>
            <Value Time="1970-01-01T00:04:00.000+01:00" Value="1"/>
            <Value Time="1970-01-01T00:05:00.000+01:00" Value="0"/>
        </TimedState>
        <TimedState Id="@floatState" Name="Float State" Type="Float">
            <Value Time="1970-01-01T00:00:00.000+01:00" Value="1.1"/>
            <Value Time="1970-01-01T00:01:00.000+01:00" Value="2.2"/>
            <Value Time="1970-01-01T00:02:00.000+01:00" Value="3.3"/>
            <Value Time="1970-01-01T00:03:00.000+01:00" Value="2.2"/>
            <Value Time="1970-01-01T00:04:00.000+01:00" Value="1.1"/>
            <Value Time="1970-01-01T00:05:00.000+01:00" Value="0.0"/>
        </TimedState>
        <TimedState Id="@stringSetState" Name="StringSet State" Type="StringSet">
            <Value Time="1970-01-01T00:00:00.000+01:00" Value="foo"/>
            <Value Time="1970-01-01T00:01:00.000+01:00" Value="foo, bar"/>
            <Value Time="1970-01-01T00:02:00.000+01:00" Value="bar"/>
        </TimedState>
        <Policies>
            <Policy Type="PlanningPolicy" Value="key:SimplePlanning"/>
            <Policy Type="ConfirmationPolicy" Value="key:NoConfirmation"/>
        </Policies>
    </Resource>
</StrolchModel>

=== strolch-li/strolch/model/src/test/resources/data/StrolchModelAll.xml
<?xml version="1.0" encoding="UTF-8"?>
<StrolchModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://strolch.li/schema/StrolchModel.xsd" xsi:schemaLocation="https://strolch.li/schema/StrolchModel.xsd https://strolch.li/xsd/StrolchModel-2.0.xsd">

	<IncludeFile file="Include1.xml" />
	<IncludeFile file="Include2.xml" />

	<Order Id="@test1" Name="Test Order" Type="Order">
		<Version Version="0" CreatedBy="test" CreatedAt="2012-11-30T18:12:05.628+01:00" Deleted="false" />
		<ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
			<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
		</ParameterBag>
		<ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
			<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
		</ParameterBag>
		<Policies>
			<Policy Type="PlanningPolicy" Value="key:SimplePlanning" />
			<Policy Type="ConfirmationPolicy" Value="key:NoConfirmation" />
		</Policies>
	</Order>

	<Resource Id="MyTestResource" Name="Test Name" Type="TestType">
		<Version Version="0" CreatedBy="test" CreatedAt="2012-11-30T18:12:05.628+01:00" Deleted="false" />
		<ParameterBag Id="@bag01" Name="Test Bag 01" Type="TestBag">
			<Parameter Id="@param8" Name="Duration Param" Type="Duration" Value="P1D" />
			<Parameter Id="@param7" Name="StringList Param" Type="StringList" Value="Hello;World" />
			<Parameter Id="@param6" Name="Date Param" Type="Date" Value="2012-11-30T18:12:05.628+01:00" />
			<Parameter Id="@param5" Name="String Param" Type="String" Value="Strolch" />
			<Parameter Id="@param4" Name="Long Param" Type="Long" Value="4453234566" />
			<Parameter Id="@param3" Name="Integer Param" Type="Integer" Value="77" />
			<Parameter Id="@param2" Name="Float Param" Type="Float" Value="44.3" />
			<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
		</ParameterBag>
		<ParameterBag Id="@bag02" Name="Test Bag 02" Type="TestBag">
			<Parameter Id="@param8" Name="Duration Param" Type="Duration" Value="P1D" />
			<Parameter Id="@param7" Name="StringList Param" Type="StringList" Value="Hello;World" />
			<Parameter Id="@param6" Name="Date Param" Type="Date" Value="2012-11-30T18:12:05.628+01:00" />
			<Parameter Id="@param5" Name="String Param" Type="String" Value="Strolch" />
			<Parameter Id="@param4" Name="Long Param" Type="Long" Value="4453234566" />
			<Parameter Id="@param3" Name="Integer Param" Type="Integer" Value="77" />
			<Parameter Id="@param2" Name="Float Param" Type="Float" Value="44.3" />
			<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
		</ParameterBag>
		<TimedState Id="@booleanState" Name="Boolean State" Type="Boolean">
			<Value Time="1970-01-01T00:00:00.000+01:00" Value="false" />
			<Value Time="1970-01-01T00:01:00.000+01:00" Value="true" />
			<Value Time="1970-01-01T00:02:00.000+01:00" Value="false" />
		</TimedState>
		<TimedState Id="@stringSetState" Name="StringSet State" Type="StringSet">
			<Value Time="1970-01-01T00:00:00.000+01:00" Value="foo" />
			<Value Time="1970-01-01T00:01:00.000+01:00" Value="foo, bar" />
			<Value Time="1970-01-01T00:02:00.000+01:00" Value="bar" />
		</TimedState>
		<Policies>
			<Policy Type="PlanningPolicy" Value="key:SimplePlanning" />
			<Policy Type="ConfirmationPolicy" Value="key:NoConfirmation" />
		</Policies>
	</Resource>

	<Activity Id="activity_1" Name="Activity" Type="parentType" TimeOrdering="Series">
		<Version Version="0" CreatedBy="test" CreatedAt="2012-11-30T18:12:05.628+01:00" Deleted="false" />
		<ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
			<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
		</ParameterBag>
		<Policies>
			<Policy Type="PlanningPolicy" Value="key:SimplePlanning" />
			<Policy Type="ConfirmationPolicy" Value="key:NoConfirmation" />
		</Policies>
		<Action Id="action_1" Name="Action 1" ResourceId="dummyId" ResourceType="dummyType" State="Created" Type="Use">
			<ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
				<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
			</ParameterBag>
			<Policies>
				<Policy Type="PlanningPolicy" Value="key:SimplePlanning" />
				<Policy Type="ConfirmationPolicy" Value="key:NoConfirmation" />
			</Policies>
			<ValueChange StateId="dummyId" Time="2012-11-30T18:12:05.628+01:00" Value="5" Type="Integer" />
			<ValueChange StateId="dummyId" Time="2012-11-30T18:12:06.628+01:00" Value="6" Type="Integer" />
		</Action>
		<Activity Id="child_activity" Name="Child Activity" Type="childType" TimeOrdering="Series">
			<ParameterBag Id="@bag01" Name="Test Bag" Type="TestBag">
				<Parameter Id="@param1" Name="Boolean Param" Type="Boolean" Value="true" />
			</ParameterBag>
			<Policies>
				<Policy Type="PlanningPolicy" Value="key:SimplePlanning" />
				<Policy Type="ConfirmationPolicy" Value="key:NoConfirmation" />
			</Policies>
			<Action Id="action_2" Name="Action 2" ResourceId="dummyId" ResourceType="dummyType" State="Planned" Type="Use">
				<ValueChange StateId="dummyId" Time="2012-11-30T18:12:05.628+01:00" Value="5" Type="Integer" />
				<ValueChange StateId="dummyId" Time="2012-11-30T18:12:06.628+01:00" Value="6" Type="Integer" />
			</Action>
			<Action Id="action_3" Name="Action 3" ResourceId="dummyId" ResourceType="dummyType" State="Created" Type="Use" />
		</Activity>
	</Activity>

</StrolchModel>
